### PR TITLE
limit file open during prepifg

### PR DESCRIPTION
**Pull request by basaks**
To address https://github.com/GeoscienceAustralia/PyRate/issues/323

### CODE REVIEW

**Review by mcgarth — CHANGES_REQUESTED** [review]
`get_analysis_extent` is also used in `pyrate/core/orbital.py` and `pyrate/core/refpixel.py`; these too will need to be modified

**Comment by richardt94** [comment]
> 
> 
> `get_analysis_extent` is also used in `pyrate/core/orbital.py` and `pyrate/core/refpixel.py`; these too will need to be modified

Is this true? Unless steps in `orbital` and `refpixel` are relying on side effects of `get_analysis_extent` by assuming the ifgs are already open then those calls should still work OK

**Comment by basaks** [comment]
yes, that is fine. Now on that function call we open the rasters as required and once they are used, the rasters are closed.
Now all the file open and close opeations are internal to get_analysis_extent childs, and the files are only open one at a time and closed asap.
Minimal files are open while using this function now.

**Review by richardt94 — APPROVED** [review]
Finally got VDI working to test the fix. Can confirm that the original issue with `prepifg` is fixed - no more complaints about file handles. I also see in the code that you've taken other steps to improve file handling.

**Comment by mcgarth** [comment]
> > `get_analysis_extent` is also used in `pyrate/core/orbital.py` and `pyrate/core/refpixel.py`; these too will need to be modified
> 
> Is this true? Unless steps in `orbital` and `refpixel` are relying on side effects of `get_analysis_extent` by assuming the ifgs are already open then those calls should still work OK

Ah yes, no need to change the calls to `get_analysis_extent` in `pyrate/core/orbital.py` and `pyrate/core/refpixel.py`

**Review by mcgarth — APPROVED** [review]

**Pull request merged**
