### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by brenmous**
0.4.0 (2019-09-12)
-----------------------
Added
+++++
- Python 3.7 support.
- Optional 'converttogeotiff' step.
- Building of docs integrated with Travis CI.
- Coherence masking, view coherence masking section in 'input_parameters.conf'
  for options.

Changed
+++++++
- 'linrate' command has been renamed to 'process'.
- CLI structure, config files now need to provided with '-f' flag.
- Reduced console output, default setting is now INFO.
- Restructure of code layout, src modules now in 'core' directory and scripts
  at top level.

Removed
+++++++
- Unused luigi code.
- References to Matlab.
- Python 3.6 support.

### CODE REVIEW

**Comment by brenmous** [comment]
closing until the above issue is resolved - will branch a new release off develop

**Comment by mcgarth** [comment]
New issue with APS correction during mpirun: https://github.com/GeoscienceAustralia/PyRate/issues/234

Otherwise things seem to work as I expect. I have not yet tested with some coherence data. Will do that once the new file handling is implemented

**Comment by brenmous** [comment]
@mcgarth requested changes implemented + parameter validation. Can we push this to master?

**Comment by brenmous** [comment]
tests are broken

**Comment by brenmous** [comment]
Tests are failing as we need to now specify refpx/py as lat/long in the config files in `test_data/small/conf`.

@sheecegardezi could you please convert the current pixel values in these config files to lat/long and provide them as the refpx/py values?

**Comment by mcgarth** [comment]
There are issues with the reference pixel conversion from latitude/longitude to pixel coordinate. I have discussed these with @sheecegardezi who is working on a fix.

Also, I think refx=0, refy=0 is a reasonable default trigger to make the refpixel search run - this lat/lon coord is in the ocean (see below image). InSAR (and thus this software) is limited to use over land. So it is 'safe' for the old condition of refx or refy = 0 to trigger the refpixel search.

image

**Comment by sheecegardezi** [comment]
New pull request will be created.

**Pull request closed without merging**
