### PR TITLE
Co/plot scripts

### PR DESCRIPTION
**Pull request by chandra2ga**
This PR is about including additional python plot scripts for visualization. This includes three plot scripts:
1) plot_time_series_errbar_vel_err_rsqr.py :  
      - Displaying linear velocity, linear error, and rsquare maps on a common window
      - Plot displacement time-series with error-bars for selected location
2) LOS_tscuml_animation.py:
     - Produce animated gif files from the tscuml files for time-series displacement
3) plot_vel_profile.py:
    - Generate velocity profile across two user selected locations over the geotif file

Other details are highlighted in PIS-154: https://gajira.atlassian.net/secure/RapidBoard.jspa?rapidView=480&projectKey=PIS&modal=detail&selectedIssue=PIS-154

### CODE REVIEW

**Review by NMoghaddam — CHANGES_REQUESTED** [review]
Thanks for the effort @chandra2ga on the improvements of the plotting scripts. As I tested the scripts on processed S1 scenes by PyRate for Mexico, I would like to make a few suggestions: 
- For `plot_time_series_errbar_vel_err-rsqr.py `script: 
Everything looks good except when checking the areas with high-velocity values. Part of the plot will be out of the window. I would suggest adjusting the window based on cumulative displacement (mm) values rather having a static window size. 
Changing the colour of three last fitting models to red to comply with the legend for PyRate linear rate symbol. Also, I am not sure, it is good to add the tscuml and its symbol in the legend as you used to include. 
- For` LOS_tscuml_animation.py` script: 
Change the location of date to be in the top centre of the plot or may have a scale bar that shows the change in the time span. 
The speed is too high. Maybe you can increase the interval=2 in `animation.ArtistAnimation` 
- For `plot_vel_profile.py `script: 
Everything is correct except I still have an issue with the sign when it comes to velocity profile. There might be useful to have a note which colour showing what type of movement since the velocity profile is a good indicator of where is subsiding and where uplifting. At this stage, the areas in high value are in blue (potential subsidence) and areas in low value are in red (potential uplift).

**Review by adeane-ga — APPROVED** [review]
Yeah thanks Chandra, these changes are awesome!!

I have also operated the co/plot_scripts branch on Mexico data CROP-B and some of my comments are probably quite similar to Negin's (mostly based on the scale bar limit). But generally everything worked - I have approved, with some comments for possible changes. 

`plot_time_series_errbar_vel_err_rsqr.py`

- Both the raster scale bar and the time series axis are not able to adapt to the Mexico velocities. Could potentially implement adaptive scale limits.
- a potential addition (but maybe not necessary) is to state on the plot what level the uncertainty is at for the velocity (in title) and also for the error-bars on plot. 

image

`LOS_tscuml_animation.py`
- The raster scale bar has the same limitation as above point, see image below as it saturates into blue because it is hitting the limit. 

image

`plot_vel_profile.py`
- again scale bar could be adapted
- would it be possible to skip the "would you like to continue? (y/n)" and have the ability click the plot again to refresh for a new profile line (?) - _I have a question mark here because there is probably quite a bit of work to change it, so certainly not a mandatory change, because it works fine as is_

image

**Comment by chandra2ga** [comment]
Thanks @neginmoghaddam and @adeane-ga for all the suggestion for the plot script. Here I updated all the 3 plot scripts considering all of your feedbacks.
Major changes are as follows:
1. **plot_time_series_errbar_vel_err_rsqr.py**: Included adaptive scale bar limit for velocity and displacement time-series, changed model fitting color, and included tscuml legend to the time-series
2.  **LOS_tscuml_animation.py** : Included adaptive scale bar limit, changed date location to top center, reduced the frame speed
3. **plot_vel_profile.py** : Included adaptive scale bar limit, replaced print command asking for user input with an automatic one. 

Let me know if any further changes required. Thanks

**Comment by NMoghaddam** [comment]
Thank you @chandra2ga for the recent changes. The plotting scripts improved significantly, and I express my approval for final review. A few comments as below might be worthwhile to be considered: 
- For `plot_time_series_errbar_vel_err-rsqr.py `script: 
Everything looks perfect now just a typo issue in pixel TS graph. In the lower-left corner, we have an extra `2019` string. That would be great to be removed. 
- For` LOS_tscuml_animation.py` script: 
The changes implemented and everything looks good. Just a note on the scalebar- for Mexico dataset, for instance, the colour saturation that was reported previously was uplifted but I have concerns around the scale bar showing values between -50 and 250 with not having 0 in the middle of the bar (a.k.a stable~zero displacement)
- For `plot_vel_profile.py `script: 
It looks really good now; however, two items I would like to raise that might be an issue with Matplotlib: (a) Some times when the script is being called, there is a point already in the map (starting point), and when the user does the click, the profile will be shown (b) I tested this script a few times, and I occasionally noticed that after a 5sec pause in interaction with the map, the plot would disappear with no warning.

**Comment by adeane-ga** [comment]
@chandra2ga: I have also just done a 2nd review of the with the updates to co/plot_scripts by using the `plot_time_series_errbar_vel_err_rsqr.py`, `LOS_tscuml_animation.py`, and `plot_vel_profile.py` on the CROP-B of Mexico data.

- All requested changes have been applied for all 3 scripts and they are operating really nicely. 
- I do agree with Negin's comment on the colour scale bar origin, so if possible, it would be great  to have white automatically located at zero. This is the case for all raster plots from the 3 scripts. 
- The immediate clicking of new points to form the profile is really great, I didn't experience any issues with the figure disappearing as mentioned by Negin. 

Thanks :)

**Comment by chandra2ga** [comment]
Here I updated all the three plot scripts with zero as white color on colorbar for both velocity and displacement maps.

1) Regards to Negin comment on typo issue on plot script **plot_time_series_errbar_vel_err-rsqr.py**: The command line tslider.ax.xaxis.set_major_formatter(mdates.ConciseDateFormatter(loc_tslider)) responsible for making that changes as default. So unable to remove that print from the plot maps. 
2) Regarding the plot disappear on **plot_vel_profile.py**  as Negin mentioned: I don't have such issue while plotting. Negin might need to check some module version settings that may cause such issue.

Let me know if any other changes required for plotting. Thanks for all the suggestions and review.

**Review by mcgarth — APPROVED** [review]
These are excellent additions @chandra2ga, really useful for users to quickly visualise PyRate results!
I have committed some minor changes and tidy ups and will now merge these in to `develop`

**Pull request merged**
